trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: 'latest'

- script: terraform init
  displayName: 'Terraform Init'
  workingDirectory: 'perents'

- script: terraform validate
  displayName: 'Terraform Validate'
  workingDirectory: 'perents'

- script: terraform plan
  displayName: 'Terraform Plan'
  workingDirectory: 'perents'
